# Bloggy particulars
highlighter: "rouge"
permalink: "/:year/:title"
name: "Route 38"
description: "Insane blogging action since 2012"
future: false

plugins: ["jekyll-paginate"]

collections:
  contributors:
    output: true
    permalink: "/authors/:path/"

url: https://rt38.net
paginate: 5
excerpt_separator: "\n\n"

# Personal particulars
person:
  name: William Ellison
  email: waellison@gmail.com
  occupation: Pythonista &amp; Blogger
  phone: 865-789-7765

social:
  networks:
    linkedin:  tnwae
    github:    tnwae
    email:     waellison@gmail.com
  options:
    email:     envelope

defaults:
  -
    scope:
      path: ""
    values:
      author: "wae"
      coffee: "Yes"

encoding: UTF-8
exclude: 
  - "node_modules"
  - "gulpfile.js"
  - "Gemfile"
  - "Rakefile"
  - "Gemfile.lock"
  - "deploy.sh"
