# Bloggy particulars
highlighter: "rouge"
permalink: "/:year/:month/:title"
name: "Route 38"
description: "Insane blogging action since 2012"
future: false

plugins: ["jekyll-paginate"]

collections:
  contributors:
    output: true
    permalink: "/authors/:path/"

sass:
  sass_dir: TheChain
  style: compressed

url: https://rt38.net
paginate: 7
excerpt_separator: "\n\n"

# Personal particulars
person:
  name: William Ellison
  email: waellison@gmail.com
  occupation: Pythonista &amp; Blogger
  phone: 865-789-7765

social:
  networks:
    linkedin:  tnwae
    github:    tnwae
    email:     mail@tnwae.us
  options:
    email:     envelope-o

defaults:
  -
    scope:
      path: ""
    values:
      author: "wae"
      image: "/art/heroes/the_desktop.jpg"
      coffee: "Yes"

#markdown: rdiscount
encoding: UTF-8
exclude: 
  - "node_modules"
  - "gulpfile.js"
  - "Gemfile"
  - "Rakefile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "cleanup.sh"

# Other configs
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

