# Bloggy particulars
highlighter: "rouge"
permalink: "/:year/:month/:title"
name: "Very Special Developments"
description: "Home of one of those condescending Unix computer users since 2017"
future: false

gems: ["jekyll-paginate"]

collections:
  contributors:
    output: true
    permalink: "/authors/:path/"

sass:
  sass_dir: TheChain
  style: compressed

url: https://vsdev.org
paginate: 10
excerpt_separator: "\n\n"

# Personal particulars
person:
  name: W. Anthony Ellison
  email: mail@tnwae.us
  occupation: Rubyist &amp; Blogger
  phone: 865-630-2564

social:
  twitter:   tnwae
  github:    tnwae
  email:     mail@tnwae.us

defaults:
  -
    scope:
      path: ""
    values:
      author: "wae"
      image: "/art/lazy.png"

markdown: rdiscount
encoding: UTF-8
exclude: 
  - "node_modules"
  - "gulpfile.js"
  - "Gemfile"
  - "Rakefile"
  - "Gemfile.lock"
  - "deploy.sh"

# Other configs
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

