# Bloggy particulars
highlighter: "rouge"
permalink: "/:year/:month/:title"
name: "Very Special Developments"
description: "technical ramblings by an ex-technologist"
future: false

plugins: ["jekyll-paginate"]

collections:
  contributors:
    output: true
    permalink: "/authors/:path/"

sass:
  sass_dir: TheChain
  style: compressed

url: https://vsdev.org
paginate: 10
excerpt_separator: "\n\n"

# Personal particulars
person:
  name: W. Anthony Ellison
  email: mail@tnwae.us
  occupation: Rubyist &amp; Blogger
  phone: 865-630-2564

social:
  networks:
    github:    tnwae
    pinterest: t90photog
    email:     mail@tnwae.us
    linkedin:  tnwae
    twitter:   tnwae
  options:
    pinterest: pinterest-p
    email:     envelope-o
    github:    github-alt

defaults:
  -
    scope:
      path: ""
    values:
      author: "wae"
      image: "//files.tnwae.us/heroes/the_desktop.jpg"
      coffee: "Yes"

markdown: rdiscount
encoding: UTF-8
exclude: 
  - "node_modules"
  - "gulpfile.js"
  - "Gemfile"
  - "Rakefile"
  - "Gemfile.lock"
  - "deploy.sh"

# Other configs
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

