# Bloggy particulars
highlighter: "rouge"
permalink: "/:year/:title"
name: "Route 38"
description: "Better than Routes 1 through 37"
future: false

plugins: ["jekyll-paginate"]

url: https://waellison.blog
paginate: 5
excerpt_separator: "\n\n"

# Personal particulars
person:
  name: William Ellison
  email: waellison@gmail.com
  occupation: Pythonista &amp; Blogger
  phone: 865-789-7765

encoding: UTF-8
exclude: 
  - "node_modules"
  - "gulpfile.js"
  - "Gemfile"
  - "Rakefile"
  - "Gemfile.lock"
  - "deploy.sh"

